---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'DevOps Challenge - Uploading secrets to required AWS services'

Parameters:

  PgpKey:
    Type: String
    Default: "PgpKey"
    Description: PgpKey

  SshKey:
    Type: String
    Default: "SshKey"
    Description: SshKey

  DatabaseUsername:
    Type: String
    Default: "DatabaseUsername"
    Description: DatabaseUsername
  
  DatabasePassword:
    Type: String
    Default: "DatabasePassword"
    Description: DatabasePassword
  
  DatabaseHost:
    Type: String
    Default: "DatabaseHost"
    Description: DatabaseHost
  
  DatabasePort:
    Type: String
    Default: "DatabasePort"
    Description: DatabasePort
  
  DatabaseName:
    Type: String
    Default: "DatabaseName"
    Description: DatabaseName
  
  ApiUsername:
    Type: String
    Default: "ApiUser"
    Description: ApiUser

  ApiPassword:
    Type: String
    Default: "ApiPassword"
    Description: ApiPassword

Resources:
  DatabaseConnectionSecret:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: DatabaseConnectionSecret
      Description: "Details required for Database connection"
      SecretString: !Sub '{"username": "${DatabaseUsername}","password": "${DatabasePassword}","engine": sqlserver,"host": "${DatabaseHost}","port": "${DatabasePort}","dbname": "${DatabaseName}"}'

  ApiServiceAccountSecret:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: ApiServiceAccountSecret
      Description: "API Service Account details"
      SecretString: !Sub '{"username": "${ApiUsername}","password": "${ApiPassword}"}'

  PgpKeySecret:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: PgpKeySecret
      Description: "PGP key details"
      SecretString: !Ref PgpKey

  SshKeySecret:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: SshKeySecret
      Description: "SSH key details"
      SecretString: !Ref SshKey


  



